apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: sumit
spec:
  tasks:
    - name: git-kus
      taskRef:
        kind: Task
        name: git-kustomize
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
