apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval  # update the name of the deployment
  labels:
    app: approval  # update the label for the deployment
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  replicas: 1
  selector:
    matchLabels:
      app: approval  # update the selector for the deployment
  template:
    metadata:
      labels:
        app: approval  # update the label for the pod template
    spec:
      imagePullSecrets:
        - name: quay
      containers:
      - name: approval  # update the name of the container
        image: quay.io/sumitbiswal/approval:f_b
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: logs-volume
            mountPath: /var/log/myapp  # update the mount path
        ports:
        - containerPort: 8080
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: approval
---
apiVersion: v1
kind: Service
metadata:
  name: approval  # update the name of the service
spec:
  selector:
    app: approval  # update the selector for the service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
