apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-approval-email
  namespace: approval

spec:
  params:
    - description: Name of the application
      name: name
      type: string
    - description: URL of the console output
      name: build-url
      type: string
    - description: Email address to send the approval request to
      name: email-to
      type: string
  steps:
    - args:
        - |
          git clone 
          echo "From: sender@example.com" > message.txt
          echo "To: $(params.email-to)" >> message.txt
          echo "Subject: Deployment Approval" >> message.txt
          echo "Content-Type: text/html" >> message.txt
          echo "" >> message.txt
          cat /workspace/config/approval-form/approval-form.html >> message.txt
          cat message.txt | /usr/sbin/sendmail -t
      command:
        - sh
        - '-c'
      image: 'python:3'
      name: send-email
      resources: {}
      volumeMounts:
        - mountPath: /workspace/config
          name: config
    - args:
        - |
          apk add --no-cache curl
          while true; do
            response=$(curl -s -X POST http://localhost:8080/approve -d "approval=$(cat /workspace/response/approval)")
            if [ -n "$response" ]; then
              echo $response > /workspace/response/result
              break
            fi
            sleep 1
          done
      command:
        - sh
        - '-c'
      image: 'alpine:3'
      name: wait-for-response
      resources: {}
      volumeMounts:
        - mountPath: /workspace/response2
          name: response-data
  volumes:
    - emptyDir: {}
      name: response-data
    - configMap:
        name: approval-form
      name: config
  workspaces:
    - name: response
